Update placeholder -> Update placeholder empty data
Nataniel-Antosik/Bench_Project pull request #135
Opened 2023-04-16 20:49 UTC by Nataniel-Antosik

### Movie list
<p align="center">
  <img src="https://user-images.githubusercontent.com/57491794/232334652-546051d3-1e0d-4c58-90d0-f1ed304e2ac6.png" width="350" title="Light mode">
  <img src="https://user-images.githubusercontent.com/57491794/232334653-b25b8ed1-ca95-4a4a-92de-be27bcd9ee35.png" width="350" title="Dark mode">
</p>

### Movie details
<p align="center">
  <img src="https://user-images.githubusercontent.com/57491794/232334655-abfddfda-dd5e-4a0a-a40b-3bf8dbc14041.png" width="350" title="Light mode details">
  <img src="https://user-images.githubusercontent.com/57491794/232334654-c04753c0-a553-47bb-943a-114f08d8c711.png" width="350" title="Dark mode details">
</p>

2023-05-10 09:08 UTC, BorysChajdas requested changes

2023-05-10 09:08 UTC, BorysChajdas commented on app/src/main/res/layout/empty_database_placeholder.xml
> +            app:landscapeHeight="@{110}"
Instead of Binding Adapter you can create resource files per orientation

2023-05-15 12:05 UTC, Nataniel-Antosik commented on app/src/main/res/layout/empty_database_placeholder.xml
> +            app:landscapeHeight="@{110}"
Done :D

2023-05-15 12:17 UTC, BorysChajdas approved these changes

2023-05-15 12:28 UTC, merged