RecyclerView popular movies -> Add adapter to recyclerView for popular movies
Nataniel-Antosik/Bench_Project pull request #18
Opened 2022-06-20 14:04 UTC by Nataniel-Antosik

2022-06-23 10:32 UTC, BorysChajdas requested changes

2022-06-27 10:01 UTC, BorysChajdas requested changes

2022-06-27 10:01 UTC, BorysChajdas commented on app/src/main/java/com/example/benchproject/app/popular/movies/view/PopularMoviesFragment.kt
> +        val popularMoviesRecyclerAdapter = PopularMoviesRecyclerAdapter()
Why it is a `val`, it's used only once, you can inline it?

2022-06-27 10:01 UTC, BorysChajdas commented on app/src/main/java/com/example/benchproject/app/popular/movies/view/PopularMoviesRecyclerAdapter.kt
> +    private var oldMovieList = emptyList<Movie>()
Why it's named `old`? It's misleading, it is not an old movie list, it is a current movie list, probably it should be named just `movies`.

2022-06-27 10:01 UTC, BorysChajdas commented on app/src/main/java/com/example/benchproject/app/popular/movies/view/PopularMoviesRecyclerAdapter.kt
> +    fun uploadMovieData(newMovieList: List<Movie>) {
`newMovieList` -> `newMovies` or just `movies`, don't add type to names

2022-06-27 10:02 UTC, BorysChajdas commented on app/src/main/java/com/example/benchproject/app/popular/movies/view/PopularMoviesRecyclerAdapter.kt
> +    @SuppressLint("NotifyDataSetChanged")
Is this warning still present? If yes you should care about it, not Supress or ignore it

2022-06-27 12:13 UTC, Nataniel-Antosik commented on app/src/main/java/com/example/benchproject/app/popular/movies/view/PopularMoviesFragment.kt
> +        val popularMoviesRecyclerAdapter = PopularMoviesRecyclerAdapter()
I thought this variable helped to make this more readable but yes it is not necessary and now it looks better :D

2022-06-27 12:14 UTC, Nataniel-Antosik commented on app/src/main/java/com/example/benchproject/app/popular/movies/view/PopularMoviesRecyclerAdapter.kt
> +    private var oldMovieList = emptyList<Movie>()
Ok, I understand and I changed it

2022-06-27 12:17 UTC, Nataniel-Antosik commented on app/src/main/java/com/example/benchproject/app/popular/movies/view/PopularMoviesRecyclerAdapter.kt
> +    fun uploadMovieData(newMovieList: List<Movie>) {
Ok, I used `newMovies` because my current list now is `movies`

2022-06-27 12:19 UTC, Nataniel-Antosik commented on app/src/main/java/com/example/benchproject/app/popular/movies/view/PopularMoviesRecyclerAdapter.kt
> +    @SuppressLint("NotifyDataSetChanged")
I understand

2022-06-27 14:08 UTC, BorysChajdas approved these changes

2022-06-28 06:32 UTC, merged